Add ability to disable/enable password authentication
spatie/ssh pull request #42
Opened 2021-03-09 12:18 UTC by MatusBoa

2021-03-09 16:42 UTC, freekmurze requested changes
Thanks! Only needs an extra test. Could you also update the readme with an example?

2021-03-09 16:42 UTC, freekmurze commented on tests/SshTest.php
> +    public function it_can_disable_password_authentication()
Could you add a test for the `enable` variant as well. I think you'll find that the current code is broken.

2021-03-09 20:46 UTC, MatusBoa commented
> Thanks! Only needs an extra test. Could you also update the readme with an example?

You are right, sorry for that. I Added and example to readme.

2021-03-10 13:40 UTC, merged

2021-03-10 13:41 UTC, freekmurze commented
Thank you!